# Generated by Django 3.0.5 on 2024-03-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_eventregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
