# Generated by Django 3.0.5 on 2024-03-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_delete_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherExtra',
        ),
    ]
